import fp
import intern
import souffle_lib
import souffle_types
relation RA(_x:Tnumber)
relation RB(_x:Tnumber)
RA((- (2147483648))).
RB((2147483647)).
output relation RC(_x:Tnumber)
output relation RD(_x:Tnumber)
RC(_x) :- Ragg(_x).
relation Ragg(_x:Tnumber)
Ragg(_x) :- tpl in RA(_y), var _x = ((tpl), _y).group_by(()).souffle_group_max().

RD(_x) :- Ragg_0(_x).
relation Ragg_0(_x:Tnumber)
Ragg_0(_x) :- tpl_0 in RB(_y), var _x = ((tpl_0), _y).group_by(()).souffle_group_min().

