import fp
import intern
import souffle_lib
import souffle_types
relation RReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames(_n1:Tnumber, _n2:Tnumber)
RReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames((1), (2)).
RReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames((2), (3)).
relation RAnotherReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames(_n1:Tnumber, _n2:Tnumber)
RAnotherReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames(_n, _m) :- RReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames(_n, _), RReallyLongNameForARelationToCheckIfThereIsAnyProblemWithSuchLongNames(_m, _), (_n < _m).
