import fp
import intern
import souffle_lib
import souffle_types
relation RBase(_X:Tnumber)
input relation RBase_shadow(_X:Tnumber)
RBase(_X) :- RBase_shadow(_X).
relation RA(_X:Tnumber)
relation RB(_X:Tnumber)
RA(_X) :- RBase(_X).
RA(_X) :- RB(_X), RBase(_X).
RB(_X) :- RA(_X), (_X != (0)).
relation RC(_X:Tnumber)
RC(_X) :- RBase(_X), not RB(_X).
output relation RQuery(_X:Tnumber)
RQuery(_X) :- RC(_X), RA(_X).
