
.decl A(n:number,d:number) 
.input A()
.decl B(n:number,s:number) 
.input B()

.decl COO(n:number,id:number) 
COO(n,id) :-   A(n,id),    B(id,max  s : {A(n,d), B(d,s)}).

.decl C2(n:number,id:number,s:number) 
C2(n,id,Y) :-   A(n,id),    B(id,Y),   Y = max  s : {A(n,d), B(d,s)}.

.decl C3(n:number,id:number) 
C3(n,id) :-   A(n,id),   B(id,Y),   2 * Y + 1 =  2 * max  s : {A(n,d), B(d,s)} + 1.

.decl C4(n:number,id:number) 
C4(n,id) :-    A(n,id),   B(id,Y),   Y =  max  s : {A(n,d), B(d,s)} .

