

.decl rel(reallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting: number, n2: number) 


rel(0, 1).
rel(0, 2).
rel(1, 2).

rel(thisIsAnotherreallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting, m) :-   rel(thisIsAnotherreallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting, _ ),  rel(m, _),  thisIsAnotherreallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting < m.
